### ISSUE TITLE
More information on csv files used

### ISSUE THREAD

**Issue by Sandhya-Bairi** [pmsosa/CS291K#1]
Could you give some information on csv files used, their contents etc?

**Comment by pmsosa** [comment]
If you want it to get to work right away all you really need is two files of good and bad tweets respectively. These are essentially just a massive list of tweets (a single tweet per line). 

When you run train.py these will get fed in by line 56 & 57, and then everything will work nicely.
https://github.com/pmsosa/CS291K/blob/59eac862b6a12f862e43ba2268a8bfcf6ddd8181/train.py#L56
https://github.com/pmsosa/CS291K/blob/59eac862b6a12f862e43ba2268a8bfcf6ddd8181/train.py#L57

Feel free to refer to the research paper too: https://www.academia.edu/35947062/Twitter_Sentiment_Analysis_using_combined_LSTM-CNN_Models

**Comment by Sandhya-Bairi** [comment]
Thank you for the information. The paper is also good. 
My another doubt is, does it take a long time to load the whole glove file every time we run?

**Comment by pmsosa** [comment]
Yea, I don't remember the specific timing, but it probably did take a minute or two.
