### ISSUE TITLE
Error: terminate called recursively; Aborted(core dumped)

### ISSUE THREAD

**Issue by Sandhya-Bairi** [pmsosa/CS291K#2]
After googling the error, i tried reducing batch size from 128 to 64 .. 8. No matter how many times I run, training goes fine but in evaluation I am getting this error in the beginning. 

> terminate called after throwing an instance of 'std::bad_alloc'
> what(): std::bad_alloc
> terminate called recursively
> Aborted(core dumped)
> 

Any suggestions?

**Comment by pmsosa** [comment]
It seems as though you are running out of memory. I'm unsure what to suggest as I never ran into that problem. Are you running inside a VM? if so perhaps check the memory allowance you have given it.
