### ISSUE TITLE
glove.6B.50d.txt file missing

### ISSUE THREAD

**Issue by susikka** [pmsosa/CS291K#4]
Where do I find or how do I generate glove.6B.50d.txt file ?

**Comment by pmsosa** [comment]
GLoVE pre-trained word embeddings can be found at: https://nlp.stanford.edu/projects/glove/

**Comment by manzilsubedi** [comment]
can you help ? where to keep the downloaded file ?

**Comment by pmsosa** [comment]
Again, look at the link posted above.
If not here's an alternate link: https://www.kaggle.com/watts2/glove6b50dtxt
